require:
  - rubocop-performance
  - rubocop-rspec

inherit_gem:
  relaxed-rubocop: .rubocop.yml

AllCops:
  TargetRubyVersion: 3.1.1

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/ClassVars:
  Enabled: false

Layout/LineLength:
  Max: 120

RSpec/MultipleExpectations:
  Enabled: false