version: "3.9"  # optional since v1.27.0
services:
  app:
    build: .
    stdin_open: true
    tty: true
    volumes:
      - ~/.ssh:/root/.ssh
      - bundle_cache:/bundle
      - .:/app

volumes:
  bundle_cache: {}